apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "<PROJECT_ID>-<AUTH_APP_LABEL>-auth"
  namespace: <PROJECT_ID>
spec:
  selector:
    matchLabels:
      app: <AUTH_APP_LABEL>
  action: CUSTOM
  provider:
    name: "opa.<PROJECT_REP_ID>"
  rules:
  - to:
    - operation:
        # notPaths: ["/ip"]
        notPaths: ["/healthz"] 