apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: "test-auth"
spec:
  selector:
    matchLabels:
      app: productpage
  action: CUSTOM
  provider:
    name: "opa.sweetpanda"
  rules:
  - to:
    - operation:
        # notPaths: ["/ip"]
        notPaths: ["/healthz"] 